// Testing requests

// Get all
GET http://localhost:3000/customers

###

// Get one
GET http://localhost:3000/customers/642182a85caa31e1771adf4d

###

// New customer
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Kalle Asiakas",
    "dateOfBirth": "2000-03-25",
    "joiningDate": "2022-07-23",
    "phoneNumber": "0947504723",
    "email": "kalle.asiakas@email.net",
    "address": "Asiakkaankatu 1",
    "membership": true
}

###

// Delete one
DELETE http://localhost:3000/customers/64217eb96458be27e7992754


###

// Update

PATCH http://localhost:3000/customers/642182a85caa31e1771adf4d
Content-Type: application/json

{
    "name": "Essi Ostaja"
}
